### PR TITLE
Initial draft of Fine Uploader application to JS Foundation

### PR DESCRIPTION
**Pull request by rnicholus**
I have put together an initial draft of the application. Please let me know how I can best improve this application and abide by the the foundation's policies, as well as the next steps in the process. Thank you for your time, and for creating this foundation.

### CODE REVIEW

**Comment by kborchers** [comment]
Thank you for reaching out @rnicholus! We will do an initial review and let you know if we have any questions or comments via comments on this PR.

@dmethvin Would you please do an initial review of the PR for completeness or any initial questions you might have and then we can discuss after that. Thanks!

**Comment by kborchers** [comment]
@rnicholus I am going to update the application template to include this but could you also send a quick email to projects at js.foundation so we have a private communication channel as well in case there are more sensitive questions/topics to discuss. This may not be common among projects but it will be good to have that channel for all applications. Thanks!

**Comment by rnicholus** [comment]
Absolutely @kborchers. I'll send an email now.

**Comment by dmethvin** [comment]
Hi @rnicholus, I'm reviewing the application now. No specific comments on what is in the applications, but I'll review with Kris and can circle back with you soon for more discussion.

**Comment by rnicholus** [comment]
Thanks for the update @dmethvin.

**Comment by rnicholus** [comment]
Hi there - I'm just checking in to see if I can do anything further or if there are perhaps some updates you're able to share. Thanks!

**Comment by kborchers** [comment]
Hey @rnicholus sorry for the delay here. I just want you to know that we have not forgotten about you and it's unfortunately just the nature of a mostly volunteer run org. I know @dmethvin has been very busy but the TAC is growing which will help with this workload so hopefully you will have more definitive guidance soon.

**Comment by rnicholus** [comment]
Thanks for the update. I certainly understand that myself given my involvement in FOSS projects. Didn't mean to come off as impatient.

**Comment by dmethvin** [comment]
Thank you for the application. The TAC has considered it and decided not to accept.

**Pull request closed without merging**
