### PR TITLE
Rename sonar to webhint

### PR DESCRIPTION
**Pull request by molant**

### CODE REVIEW

**Comment by dmethvin** [comment]
Congrats @molant! I really like the new name. @kborchers do you have a preference on how we should handle renames in historical documents like this? I think it's useful to put *some sort* of reference in here to both names. Perhaps a note at the top that says, "Note: webhint originally joined the JS Foundation as Sonar but the project changed its name in August 2018 to better reflect its mission as a linter for the web."

**Comment by kborchers** [comment]
So sorry all! For some reason I have not been getting any GitHub notifications, even when directly mentioned and I don't think I changed anything. I agree with Dave. Can you add a note at the top of the application that states webhint originally joined the JSF as sonar and then changed the name? I don't think we need to have the sonar -> sonarwhal called out and in fact, you could probably just say it was originally named sonarwhal then changed to webhint. Either way would work for me.

**Comment by jorydotcom** [comment]
Hey @molant - I'd love to get this PR merged for you! Would you like me to make the requested change on your behalf?

**Comment by molant** [comment]
Yes please!


________________________________

**Comment by jorydotcom** [comment]
Okiedokie - this was a pretty straightforward request, so I will go ahead and merge and beg forgiveness if that was not OK cc @dmethvin 😄

**Pull request merged**
